title: Neill's Website
description: Personal website - blog, album, reading list
url: "https://www.neillperry.com"
baseurl: ""

markdown: kramdown
parse_block_html: true
permalink: /blog/:year/:month/:day/:title

include: ['_pages']

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Neill Perry"